version: "3"

services:
  caddy:
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy/config:/config
      - ./data/caddy/data:/data
    image: caddy:alpine

  libretranslate:
    container_name: libretranslate
    restart: always
    volumes:
      - ./data/libretranslate/LibreTranslate:/root/.local/share/LibreTranslate
      - ./data/libretranslate/argos-translate:/root/.local/share/argos-translate
    image: libretranslate/libretranslate:latest
    command: --frontend-language-target en

  translate:
    container_name: translate
    restart: always
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/v1/health || exit 1"]
    image: ghcr.io/tooot-app/translate:latest
