name: Build production
on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: api
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: -- Step 1 -- Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: -- Step 2 -- Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: -- Step 3 -- Install dependencies
        run: yarn install
      - name: -- Step 4 -- Build js
        run: yarn build
      - name: -- Step 6 -- Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: -- Step 7 -- Get version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: api
      - name: -- Step 8 -- Build and push
        uses: docker/build-push-action@v2
        with:
          context: api
          push: true
          tags: |
            ghcr.io/tooot-app/translate:latest
            ghcr.io/tooot-app/translate:${{ steps.package-version.outputs.current-version}}